// <auto-generated />
using System;
using Labb2_LINQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2_LINQ.Migrations
{
    [DbContext(typeof(LinqSchoolDbContext))]
    partial class LinqSchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb2_LINQ.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "1A"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "1B"
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "2A"
                        },
                        new
                        {
                            ClassId = 4,
                            ClassName = "2B"
                        });
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Programming 1"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Programming 2"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "English"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Social Sciences"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Economics"
                        });
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ClassId = 1,
                            StudentFirstName = "Ellen",
                            StudentLastName = "Berg",
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            ClassId = 2,
                            StudentFirstName = "Erik",
                            StudentLastName = "Karlsson"
                        },
                        new
                        {
                            StudentId = 3,
                            ClassId = 3,
                            StudentFirstName = "Karolin",
                            StudentLastName = "Jonsson"
                        },
                        new
                        {
                            StudentId = 4,
                            ClassId = 4,
                            StudentFirstName = "Jonas",
                            StudentLastName = "Ytterbom"
                        },
                        new
                        {
                            StudentId = 5,
                            ClassId = 4,
                            StudentFirstName = "Patricia",
                            StudentLastName = "Larsson"
                        },
                        new
                        {
                            StudentId = 6,
                            ClassId = 2,
                            StudentFirstName = "Rickard",
                            StudentLastName = "Svensson"
                        },
                        new
                        {
                            StudentId = 7,
                            ClassId = 2,
                            StudentFirstName = "Klara",
                            StudentLastName = "Hedman",
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 8,
                            ClassId = 3,
                            StudentFirstName = "Hampus",
                            StudentLastName = "Lagergren"
                        },
                        new
                        {
                            StudentId = 9,
                            ClassId = 2,
                            StudentFirstName = "Lisa",
                            StudentLastName = "Löf"
                        },
                        new
                        {
                            StudentId = 10,
                            ClassId = 1,
                            StudentFirstName = "Kalle",
                            StudentLastName = "Broman",
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 11,
                            ClassId = 2,
                            StudentFirstName = "Erik",
                            StudentLastName = "Bergman",
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 12,
                            ClassId = 2,
                            StudentFirstName = "Johan",
                            StudentLastName = "Larsson",
                            TeacherId = 2
                        },
                        new
                        {
                            StudentId = 13,
                            ClassId = 4,
                            StudentFirstName = "Johanna",
                            StudentLastName = "Eriksson",
                            TeacherId = 1
                        },
                        new
                        {
                            StudentId = 14,
                            ClassId = 3,
                            StudentFirstName = "Gunilla",
                            StudentLastName = "Olsson",
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("Labb2_LINQ.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 4
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 5
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 9,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 10,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 11,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 12,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 13,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 14,
                            CourseId = 1
                        });
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("TeacherFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeacherLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            TeacherFirstName = "Reidar",
                            TeacherLastName = "Nilsen"
                        },
                        new
                        {
                            TeacherId = 2,
                            TeacherFirstName = "Tobias",
                            TeacherLastName = "Landén"
                        },
                        new
                        {
                            TeacherId = 3,
                            TeacherFirstName = "Aldor",
                            TeacherLastName = "Besher"
                        });
                });

            modelBuilder.Entity("Labb2_LINQ.Models.TeacherCourse", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("TeacherCourses");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            TeacherId = 3,
                            CourseId = 2
                        },
                        new
                        {
                            TeacherId = 1,
                            CourseId = 3
                        },
                        new
                        {
                            TeacherId = 3,
                            CourseId = 4
                        },
                        new
                        {
                            TeacherId = 2,
                            CourseId = 5
                        },
                        new
                        {
                            TeacherId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            TeacherId = 1,
                            CourseId = 4
                        });
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Student", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb2_LINQ.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.StudentCourse", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb2_LINQ.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.TeacherCourse", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb2_LINQ.Models.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Course", b =>
                {
                    b.Navigation("StudentCourses");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Teacher", b =>
                {
                    b.Navigation("TeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
